Add support for custom endpoint pathnames
axa-group/oauth2-mock-server pull request #152
Opened 2021-12-23 12:08 UTC by roskh

## PR Checklist

- [ X ] I have run `npm test` locally and all tests are passing.
- [ X ] I have added/updated tests for any new behavior.
- [ X ] If this is a significant change, an issue has already been created where the problem / solution was discussed: https://github.com/axa-group/oauth2-mock-server/issues/151

## PR Description

Add options object to override default endpoint pathnames to support some OAuth2 clients which have different hardcoded paths

2021-12-23 12:11 UTC, roskh commented
Along with this PR https://github.com/axa-group/oauth2-mock-server/pull/150
this OAuth2 mock library now can support mocking an Auth0 AS (redirect-based authorization code flow)

2021-12-26 20:55 UTC, nulltoken commented
@poveden LGTM. How about you?

2021-12-27 11:13 UTC, poveden requested changes
Looks fine to me. Could you please rebase against `master`?

I must say that I cannot imagine how there can be client libraries that have hardcoded paths, as it's the server who gets to decide them. Maybe I'm missing something?

2022-01-10 09:15 UTC, roskh commented
> Looks fine to me. Could you please rebase against `master`?
> 
> I must say that I cannot imagine how there can be client libraries that have hardcoded paths, as it's the server who gets to decide them. Maybe I'm missing something?

Sorry for my late reply (was on holidays 😅)

In my cause I'm using the [Auth0 client library for java](https://github.com/auth0/auth0-java) to communicate with the Auth0 servers, which from what I can see [doesn't allow one to specify custom endpoints paths](https://github.com/auth0/auth0-java/blob/4f851c8390f9c696fa0cef283ae6bbd0ad826eda/src/main/java/com/auth0/client/auth/AuthAPI.java#L638-L643).

I have also taken the liberty to update my PR to improve the new interface

2022-01-12 00:26 UTC, poveden approved these changes

2022-01-12 00:31 UTC, merged