Support the token introspection endpoint
axa-group/oauth2-mock-server pull request #164
Opened 2022-01-28 07:15 UTC by cfman

## PR Checklist

- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here] #160 

## PR Description

Support the token introspection endpoint and the default endpoint is `/introspect`

2022-01-31 10:48 UTC, poveden approved these changes

2022-01-31 11:14 UTC, nulltoken requested changes

2022-02-01 11:18 UTC, cfman commented on README.md
> +It simulates the [token introspection endpoint](https://www.oauth.com/oauth2-servers/token-introspection-endpoint/).
Updated

2022-02-01 12:39 UTC, nulltoken approved these changes

2022-02-01 12:45 UTC, merged

2022-02-01 12:45 UTC, nulltoken commented
@cfman Awesome! 👍