Bump dependencies
axa-group/oauth2-mock-server pull request #299
Opened 2023-12-09 18:38 UTC by nulltoken

## PR Checklist

- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]

## PR Description

The title says it all :wink:

2023-12-09 18:39 UTC, nulltoken commented on .vscode/settings.json
> +    "source.fixAll": "explicit"
Result of an eslint bump

2023-12-09 18:40 UTC, nulltoken commented on tsconfig.json
> +    "skipLibCheck": true
cf. https://vitejs.dev/guide/migration.html#rollup-4

"If you are using TypeScript, make sure to set moduleResolution: 'bundler' (or node16/nodenext) as Rollup 4 requires it. Or you can set skipLibCheck: true instead."

2024-11-22 19:02 UTC, nulltoken commented
@poveden Here it is. Updated.

2024-11-25 09:15 UTC, poveden requested changes

2024-11-25 13:58 UTC, poveden approved these changes

2024-11-25 14:41 UTC, merged