Add nonce support
axa-group/oauth2-mock-server pull request #34
Opened 2020-08-24 07:30 UTC by HASHIMOTO-Takafumi

## PR Checklist

- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: N/A

## PR Description

The PR adds nonce support to mock OIDC authentication server.
`authorizeHandler()` changed to be non-static in order to store nonce values in the server's state.

2020-09-08 09:02 UTC, poveden requested changes
@HASHIMOTO-Takafumi Thanks for this PR!

I can see that this code will work well if the caller issues calls to the authorization and token endpoints in sequence, but it will break if 2 or more requests enter in parallel, which I believe will be a common case while running a battery of tests.

Since the nonce is a state variable, could you please, instead of keeping the nonce as a single variable, add a dictionary with authorization_code/nonce as key/value pairs? This way we could ensure that the right nonce is delivered to the right request.

2020-09-17 09:02 UTC, HASHIMOTO-Takafumi commented
Thank you for reviewing. I've fixed the problem.

2020-09-30 11:09 UTC, poveden approved these changes

2020-09-30 11:10 UTC, merged

2020-09-30 11:10 UTC, poveden commented
@HASHIMOTO-Takafumi sorry for the delay. It is done. Thank you so much!

2020-10-01 11:35 UTC, poveden commented
@HASHIMOTO-Takafumi I've just [published version 2.0.0 to npm](https://www.npmjs.com/package/oauth2-mock-server). Thanks again!